const decks=[
 {id:'daily',type:'vocabulary',icon:'朝',title:'Daily Life',subtitle:'Everyday routines & time',cards:[['起きる','おきる','to wake up','毎朝六時に起きます。— I wake up at six every morning.'],['間に合う','まにあう','to be in time','電車に間に合いました。— I made it in time for the train.'],['準備','じゅんび','preparation','旅行の準備をしています。— I am preparing for the trip.'],['片付ける','かたづける','to tidy up','部屋を片付けてください。— Please tidy the room.'],['留守','るす','absence / away','母は今、留守です。— My mother is away now.'],['習慣','しゅうかん','habit','早寝はいい習慣です。— Going to bed early is a good habit.']]},
 {id:'travel',type:'vocabulary',icon:'旅',title:'Travel & Directions',subtitle:'Moving around Japan',cards:[['乗り換える','のりかえる','to transfer','新宿で地下鉄に乗り換えます。— I transfer to the subway at Shinjuku.'],['到着','とうちゃく','arrival','三時に東京へ到着します。— We arrive in Tokyo at three.'],['交差点','こうさてん','intersection','次の交差点を右へ曲がります。— Turn right at the next intersection.'],['案内所','あんないじょ','information desk','案内所で地図をもらいました。— I got a map at the information desk.'],['往復','おうふく','round trip','大阪まで往復でお願いします。— A round trip to Osaka, please.'],['遅れる','おくれる','to be late','バスが十分遅れています。— The bus is ten minutes late.']]},
 {id:'patterns',type:'grammar',icon:'文',title:'N4 Grammar Patterns',subtitle:'Useful sentence structures',cards:[['〜ながら','〜ながら','while doing','音楽を聞きながら勉強します。— I study while listening to music.'],['〜そうです','〜そうです','it looks like…','雨が降りそうです。— It looks like it will rain.'],['〜てしまう','〜てしまう','finish / regrettably do','宿題を忘れてしまいました。— I unfortunately forgot my homework.'],['〜ようになる','〜ようになる','come to be able to','漢字が読めるようになりました。— I became able to read kanji.'],['〜かもしれない','〜かもしれない','might / perhaps','明日は雪かもしれません。— It might snow tomorrow.'],['〜ために','〜ために','in order to','日本で働くために勉強しています。— I study in order to work in Japan.']]},
 {id:'work',type:'vocabulary',icon:'働',title:'Work & Society',subtitle:'Office and public life',cards:[['会議','かいぎ','meeting','午後に会議があります。— There is a meeting in the afternoon.'],['受付','うけつけ','reception desk','受付で名前を書いてください。— Please write your name at reception.'],['連絡','れんらく','contact / message','後で連絡します。— I will contact you later.'],['予定','よてい','plan / schedule','週末の予定はありますか。— Do you have plans this weekend?'],['相談','そうだん','consultation','先生に相談しました。— I consulted the teacher.'],['経験','けいけん','experience','日本で働いた経験があります。— I have experience working in Japan.']]},
 {id:'feelings',type:'vocabulary',icon:'心',title:'Feelings & Opinions',subtitle:'Express what you think',cards:[['安心','あんしん','relief / peace of mind','無事だと聞いて安心しました。— I was relieved to hear they were safe.'],['残念','ざんねん','regrettable / a pity','会えなくて残念です。— It is a pity we cannot meet.'],['驚く','おどろく','to be surprised','そのニュースに驚きました。— I was surprised by the news.'],['大切','たいせつ','important / precious','家族はとても大切です。— Family is very important.'],['賛成','さんせい','agreement','私はその意見に賛成です。— I agree with that opinion.'],['心配','しんぱい','worry','試験の結果が心配です。— I worry about the exam result.']]},
 {id:'connections',type:'grammar',icon:'結',title:'Connecting Ideas',subtitle:'Explain reasons & contrast',cards:[['〜ので','〜ので','because / since','静かなので、よく眠れます。— Since it is quiet, I can sleep well.'],['〜のに','〜のに','although / despite','勉強したのに、忘れました。— Although I studied, I forgot.'],['〜し、〜し','〜し、〜し','and also / giving reasons','安いし、おいしいし、人気です。— It is cheap, delicious, and popular.'],['〜なら','〜なら','if it is / speaking of','京都なら、秋がおすすめです。— If it is Kyoto, autumn is recommended.'],['〜ても','〜ても','even if','雨が降っても行きます。— I will go even if it rains.'],['〜という','〜という','called / named','「花」という店を知っていますか。— Do you know a shop called Hana?']]}
];
const state=JSON.parse(localStorage.getItem('nihongoGarden')||'null')||{reviewed:0,mastered:[],quizCorrect:0,quizTotal:0,today:0,lastStudy:null,streak:0};
let currentDeck=decks[0],cardIndex=0,quiz=[],quizIndex=0,answered=false;
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function save(){localStorage.setItem('nihongoGarden',JSON.stringify(state));renderStats()}
function touchStudy(){const today=new Date().toDateString();if(state.lastStudy!==today){const y=new Date(Date.now()-86400000).toDateString();state.streak=state.lastStudy===y?state.streak+1:1;state.today=0;state.lastStudy=today}state.today++;save()}
function deckProgress(d){return Math.round(d.cards.filter(c=>state.mastered.includes(d.id+':'+c[0])).length/d.cards.length*100)}
function deckCard(d){const p=deckProgress(d);return `<button class="deck-card" data-deck="${d.id}"><span class="deck-icon">${d.icon}</span><h3>${d.title}</h3><p>${d.subtitle}</p><footer><span>${d.cards.length} cards</span><div class="mini-meter"><i style="width:${p}%"></i></div><b>${p}%</b></footer></button>`}
function renderDecks(){featuredDecks.innerHTML=decks.slice(0,3).map(deckCard).join('');const f=$('.chip.active')?.dataset.filter||'all';allDecks.innerHTML=decks.filter(d=>f==='all'||d.type===f).map(deckCard).join('');$$('[data-deck]').forEach(b=>b.onclick=()=>startDeck(b.dataset.deck))}
function navigate(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===id));scrollTo({top:0,behavior:'smooth'});if(id==='progress')renderStats()}
function startDeck(id){currentDeck=decks.find(d=>d.id===id);cardIndex=0;studyTitle.textContent=currentDeck.title;showCard();navigate('study')}
function showCard(){const c=currentDeck.cards[cardIndex];flashcard.classList.remove('flipped');cardJapanese.textContent=c[0];cardReading.textContent=c[1];cardMeaning.textContent=c[2];cardExample.textContent=c[3];cardProgress.textContent=`${cardIndex+1} / ${currentDeck.cards.length}`;studyMeter.style.width=`${(cardIndex+1)/currentDeck.cards.length*100}%`}
function rate(known){const c=currentDeck.cards[cardIndex],key=currentDeck.id+':'+c[0];state.reviewed++;if(known&&!state.mastered.includes(key))state.mastered.push(key);touchStudy();cardIndex=(cardIndex+1)%currentDeck.cards.length;renderDecks();showCard()}
function makeQuiz(){const pool=decks.flatMap(d=>d.cards);quiz=[...pool].sort(()=>Math.random()-.5).slice(0,5).map(c=>{const wrong=[...new Set(pool.map(x=>x[2]).filter(x=>x!==c[2]))].sort(()=>Math.random()-.5).slice(0,3);return{c,answers:[c[2],...wrong].sort(()=>Math.random()-.5)}});quizIndex=0;showQuestion();navigate('quiz')}
function showQuestion(){answered=false;nextQuestion.disabled=true;feedback.textContent='';const q=quiz[quizIndex];quizPrompt.textContent=q.c[0];quizReading.textContent=q.c[1];quizProgress.textContent=`Question ${quizIndex+1} of ${quiz.length}`;quizMeter.style.width=`${(quizIndex+1)/quiz.length*100}%`;answers.innerHTML=q.answers.map(a=>`<button class="answer">${a}</button>`).join('');$$('.answer').forEach(b=>b.onclick=()=>answer(b,q.c[2]))}
function answer(button,correct){if(answered)return;answered=true;state.quizTotal++;const ok=button.textContent===correct;if(ok)state.quizCorrect++;button.classList.add(ok?'correct':'wrong');$$('.answer').forEach(b=>{if(b.textContent===correct)b.classList.add('correct')});feedback.textContent=ok?'よくできました！ Correct.':`Not quite — the answer is “${correct}.”`;nextQuestion.disabled=false;touchStudy()}
function renderStats(){streakCount.textContent=state.streak;todayCount.textContent=Math.min(state.today,10);reviewedStat.textContent=state.reviewed;masteredStat.textContent=state.mastered.length;accuracyStat.textContent=state.quizTotal?Math.round(state.quizCorrect/state.quizTotal*100)+'%':'—';insightTitle.textContent=state.reviewed?`${state.streak}-day rhythm in progress`:'Begin your first session';insightText.textContent=state.reviewed?`You have reviewed ${state.reviewed} cards and mastered ${state.mastered.length}. Keep the momentum gentle and steady.`:'Review a few cards today to start building your learning rhythm.'}
$$('[data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav));$$('[data-start]').forEach(b=>b.onclick=makeQuiz);$$('[data-rate]').forEach(b=>b.onclick=()=>rate(b.dataset.rate==='know'));flashcard.onclick=()=>flashcard.classList.toggle('flipped');shuffleButton.onclick=()=>{currentDeck.cards.sort(()=>Math.random()-.5);cardIndex=0;showCard()};nextQuestion.onclick=()=>{if(++quizIndex<quiz.length)showQuestion();else{navigate('progress')}};$$('.chip').forEach(b=>b.onclick=()=>{$$('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderDecks()});resetProgress.onclick=()=>{if(confirm('Reset all locally saved learning progress?')){Object.assign(state,{reviewed:0,mastered:[],quizCorrect:0,quizTotal:0,today:0,lastStudy:null,streak:0});save();renderDecks()}};
renderDecks();renderStats();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
